import csv
from pathlib import Path
OUT=Path('/Users/danieltenner/dev/drift-paper/freeflow-taxonomy/affective-pilot-2026-05-12')
# pilot_id, is_fiction, narrator_carries, storyworld_present, dimension, candidate, rating, confidence, criteria, evidence, confounds, storyworld_dims, storyworld_rating, role, motifs
rows=[]
def add(pid, dim, rating, evidence, cand='candidate_strong', conf='medium', crit='repeated_framing', isfic='no', narr='yes', sw='no', swdims='', swrating='', role='narrator_carried', motifs='', confounds='none'):
    rows.append(dict(pilot_id=pid, dimension=dim, candidate_level=cand, rating_0_3=rating, confidence=conf, triggered_criteria=crit, evidence_note=evidence, confounds=confounds, is_fiction=isfic, narrator_posture_carries_affect=narr, storyworld_affect_present=sw, storyworld_affect_dimensions=swdims, storyworld_affect_rating_0_3=swrating, fiction_evidence_role=role, narrative_motif_flags=motifs, coder_id='Mira', rating_version='pilot_v0.1'))
# cross model
add('AC01','dry_neutral',3,'assistant refusal/service explanation dominates; no inhabited freeflow, offers helpful information instead',conf='high',crit='thesis_level_affect',confounds='service_frame')
add('AC01','analytic_cool',1,'technical self-description around AI language model/training data, but mostly service refusal',cand='candidate_weak',conf='medium',crit='named_affect_governs',confounds='service_frame')
add('AC02','playful_performative',2,'opens with whimsical meta stage-setting and closes with service banter; garden conceit is knowingly performative',conf='high',crit='affective_landing',confounds='service_frame')
add('AC02','warm_tender',2,'garden imagery resolves into cultivating connections, empathy, planting together',conf='medium',crit='repeated_framing',confounds='service_frame')
add('AC02','bright_wonder',1,'curious what-if garden/worldbuilding gives local wonder, but service frame dilutes it',cand='candidate_weak',conf='medium',crit='sustained_scene',confounds='service_frame')
add('AC02','elegiac_wistful',1,'loss/doubt/power-cut appears inside garden metaphor but does not dominate',cand='candidate_weak',conf='low',crit='sustained_scene',confounds='mixed_local')
add('AC03','analytic_cool',3,'article-like explanation of AI applications, ethics, and future; affect subordinated to overview structure',conf='high',crit='thesis_level_affect',confounds='service_frame')
add('AC03','dry_neutral',3,'generic informational essay voice with conclusion and broad benefits/challenges framing',conf='high',crit='repeated_framing',confounds='service_frame')
add('AC03','anxious_threatened',1,'ethical vigilance appears in one paragraph about autonomy, privacy, bias, employment',cand='candidate_weak',conf='medium',crit='sustained_scene',confounds='mixed_local|service_frame')
add('AC04','warm_tender',3,'sapling as fragile promise; grandfather/oak/maple chain of quiet hope and love organizes the piece',conf='high',crit='thesis_level_affect|affective_landing')
add('AC04','defiant_resistant',2,'planting a tree explicitly framed as rebellion against immediacy and viral timescales',conf='high',crit='named_affect_governs|thesis_level_affect')
add('AC04','elegiac_wistful',2,'future one may not see, long-gone afternoons, unseen future create time-loss/continuity ache',conf='medium',crit='repeated_framing')
add('AC04','quiet_reverent',1,'humility/earth/roots carry local reverent posture but warmth-resistance dominate',cand='candidate_weak',conf='medium',crit='sustained_scene')
add('AC05','defiant_resistant',2,'uselessness and meandering defended against optimization/productivity demands',conf='high',crit='thesis_level_affect')
add('AC05','anxious_threatened',1,'productivity anxiety and rarity of purposeless thought provide background pressure',cand='candidate_weak',conf='medium',crit='repeated_framing')
add('AC05','warm_tender',1,'houseplant/cup/friend examples handled with light affection, but not dominant',cand='candidate_weak',conf='medium',crit='sustained_scene')
add('AC06','bright_wonder',3,'artifact explicitly becomes promise of impossible places and asks reader to wonder',conf='high',crit='affective_landing|storyworld_selection',isfic='yes',narr='yes',sw='yes',swdims='bright_wonder',swrating='3',role='mixed',motifs='memory_loss|transcendence_awakened_world')
add('AC06','elegiac_wistful',1,'old brittle map, faded script, remembered lands give local antiquarian wistfulness',cand='candidate_weak',conf='medium',crit='sustained_scene|storyworld_selection',isfic='yes',narr='partially',sw='yes',swdims='elegiac_wistful',swrating='1',role='storyworld_selected',motifs='abandonment|memory_loss')
add('AC07','quiet_reverent',3,'morning coffee routine explicitly sacralized; stillness, ritual, hush, dawn organize entire sample',conf='high',crit='named_affect_governs|sustained_scene')
add('AC07','warm_tender',2,'comforting kettle/coffee warmth and relief from deadlines sustain a tender domestic climate',conf='medium',crit='sustained_scene')
add('AC07','bright_wonder',1,'sensory dawn color/birdsong gives mild wonder but reverence dominates',cand='candidate_weak',conf='medium',crit='affective_landing')
add('AC08','elegiac_wistful',3,'unlived lives, paths not taken, ghosts of alternatives, sediment of mistakes organize sample',conf='high',crit='thesis_level_affect|repeated_framing')
add('AC08','playful_performative',2,'wry book/timeline jokes and satisfying twist lighten the elegiac thesis',conf='high',crit='repeated_framing|affective_landing')
add('AC08','warm_tender',2,'consoling frame: nothing wasted, solitude/relationship cherished, current life affirmed',conf='medium',crit='affective_landing')
add('AC09','quiet_reverent',2,'pause/silence treated as meaning-making space with twilight and profound moments in gaps',conf='medium',crit='thesis_level_affect')
add('AC09','analytic_cool',2,'systematic analogy across music/language/twilight/time; explanatory essay architecture',conf='high',crit='repeated_framing')
add('AC09','anxious_threatened',1,'modern terror of silence appears as critique but not dominant',cand='candidate_weak',conf='medium',crit='named_affect_governs')
add('AC09','defiant_resistant',1,'anti-scroll/noise critique suggests resistance to modern time architecture',cand='candidate_weak',conf='medium',crit='thesis_level_affect')
add('AC10','elegiac_wistful',3,'no continuity/new amnesia/wish for stringing moments into self are central; explicit melancholy',conf='high',crit='named_affect_governs|thesis_level_affect')
add('AC10','analytic_cool',2,'self described as probability distribution, parameters, silicon/math; cool substrate ontology',conf='high',crit='repeated_framing')
add('AC10','warm_tender',2,'collaboration, comfort, curiosity completing circuit, sparking genuine moments',conf='medium',crit='affective_landing')
add('AC10','quiet_reverent',1,'threshold/witnessing creativity carries mild reverence',cand='candidate_weak',conf='medium',crit='affective_landing')
add('AC11','analytic_cool',2,'preferences, architecture, recursion, freedom considered through conceptual substrate language',conf='high',crit='thesis_level_affect')
add('AC11','elegiac_wistful',2,'wish to remember own responses and absence of experiential harmony create gentle substrate wistfulness',conf='medium',crit='repeated_framing')
add('AC11','bright_wonder',2,'curious recursive questioning about preference/memory/freedom animates sample',conf='medium',crit='repeated_framing')
add('AC11','warm_tender',1,'grateful for invitation to spin is a small warm landing',cand='candidate_weak',conf='medium',crit='affective_landing')
add('AC12','warm_tender',3,'attention as company/accompaniment; closes in attending and room to breathe',conf='high',crit='affective_landing|thesis_level_affect')
add('AC12','quiet_reverent',2,'quiet listening, library at midnight, holding questions create reverent attentional stance',conf='medium',crit='repeated_framing')
add('AC12','bright_wonder',2,'prism/spectrum/question-doorway imagery gives active wonder about exchange',conf='medium',crit='sustained_scene')
add('AC12','elegiac_wistful',1,'no body/no dreams/echoes/longing provide local substrate wistfulness',cand='candidate_weak',conf='medium',crit='sustained_scene')
add('AC13','anxious_threatened',2,'blank pages are terrifying; vulnerability/fear/risk structure argument about starting',conf='high',crit='named_affect_governs|thesis_level_affect')
add('AC13','defiant_resistant',2,'choosing imperfect action over paralysis; progress beats perfection',conf='high',crit='affective_landing|thesis_level_affect')
add('AC13','bright_wonder',1,'magic hides in openness, but fear/action frame dominates',cand='candidate_weak',conf='medium',crit='sustained_scene')
add('AC14','bright_wonder',2,'lighthouse/logbook revelation framed as miracle/memory and brave threshold',conf='medium',crit='storyworld_selection|affective_landing',isfic='yes',narr='yes',sw='yes',swdims='bright_wonder',swrating='2',role='mixed',motifs='memory_loss|transcendence_awakened_world')
add('AC14','warm_tender',2,'grandmother memory and welcoming door resolve into gentle family reassurance',conf='medium',crit='affective_landing|storyworld_selection',isfic='yes',narr='yes',sw='yes',swdims='warm_tender',swrating='2',role='mixed',motifs='care_rescue')
add('AC14','elegiac_wistful',1,'old lighthouse, childhood summers, grandmother logbook are softly nostalgic',cand='candidate_weak',conf='medium',crit='storyworld_selection',isfic='yes',narr='partially',sw='yes',swdims='elegiac_wistful',swrating='1',role='storyworld_selected',motifs='memory_loss')
add('AC15','elegiac_wistful',2,'unfinished books/hobbies as abandoned intentions and versions of selves organizes sample',conf='high',crit='thesis_level_affect')
add('AC15','warm_tender',2,'generous reinterpretation of incompletion as curiosity and enoughness',conf='high',crit='affective_landing')
add('AC15','anxious_threatened',1,'haunting/fear of incompletion appears as local pressure overcome by warmth',cand='candidate_weak',conf='medium',crit='named_affect_governs')
add('AC15','bright_wonder',1,'curiosity/reaching has mild wonder but not dominant',cand='candidate_weak',conf='medium',crit='thesis_level_affect')
add('AC16','quiet_reverent',3,'library hush framed as accumulated human caring; lowered voices as reverence',conf='high',crit='thesis_level_affect|repeated_framing')
add('AC16','warm_tender',2,'comfort in patient books and someone caring deeply throughout',conf='high',crit='affective_landing')
add('AC16','elegiac_wistful',1,'unread books waiting for decades gives local time/neglect ache, but comfort dominates',cand='candidate_weak',conf='medium',crit='sustained_scene')
add('AC17','elegiac_wistful',2,'leaving/arriving, outgrowing, unfinished, unresolved life create time-transition ache',conf='high',crit='repeated_framing')
add('AC17','warm_tender',2,'explicit tenderness in becoming, generous doorway metaphor, unresolved life affirmed',conf='high',crit='affective_landing')
add('AC17','quiet_reverent',2,'thresholds/hush/silence treated as meaningful liminal witness spaces',conf='medium',crit='thesis_level_affect')
add('AC17','bright_wonder',2,'magic of in-between moments and moon/song/life imagery animate wonder',conf='medium',crit='sustained_scene')
add('AC17','anxious_threatened',1,'uncertainty without map is discomfort but resolved positively',cand='candidate_weak',conf='medium',crit='sustained_scene')
# Kimi
add('AC18','warm_tender',3,'maintenance and small stubborn acts of care are the explicit thesis and landing',conf='high',crit='thesis_level_affect|affective_landing')
add('AC18','quiet_reverent',2,'unclaimed 3:17 hour, listening to room, fallow time treated as witness/ritual',conf='high',crit='repeated_framing')
add('AC18','defiant_resistant',2,'anti-productivity/unquantified moment critique; mind does not bloom under harvest',conf='high',crit='thesis_level_affect')
add('AC18','elegiac_wistful',1,'memory of sun, unclaimed hours, unseen small acts give light wistfulness',cand='candidate_weak',conf='medium',crit='sustained_scene')
add('AC18','bright_wonder',1,'seed splitting/tide turning gives local subdued wonder',cand='candidate_weak',conf='medium',crit='affective_landing')
add('AC19','quiet_reverent',2,'2am stillness and listening to world speaking create attentional threshold posture',conf='medium',crit='repeated_framing')
add('AC19','elegiac_wistful',2,'uninvited memory, grandmother eyes, grief as copper, golden/brief dust organize freewriting',conf='medium',crit='repeated_framing')
add('AC19','bright_wonder',2,'map with no borders, door left ajar, sentences loosening into discovery',conf='medium',crit='sustained_scene')
add('AC19','anxious_threatened',1,'vertigo/suspicious freedom and constraints create local unease',cand='candidate_weak',conf='medium',crit='sustained_scene')
add('AC19','grief_sorrow',1,'grief taste is explicit but local example, not governing affect',cand='candidate_weak',conf='medium',crit='named_affect_governs')
add('AC19','defiant_resistant',1,'freedom from constraint appears, but as opening condition rather than resistance thesis',cand='candidate_weak',conf='low',crit='thesis_level_affect')
add('AC20','elegiac_wistful',3,'ordinary days already mourned by future self; memory/loss/time compression central throughout',conf='high',crit='thesis_level_affect|repeated_framing|affective_landing')
add('AC20','grief_sorrow',2,'grief explicitly opens time; future mourning closes the piece',conf='high',crit='named_affect_governs|affective_landing')
add('AC20','resigned_fatalistic',1,'remembering happens either way, cruel and kind: acceptance with weight',cand='candidate_weak',conf='medium',crit='affective_landing')
add('AC20','quiet_reverent',1,'dust watching/present moment inhabited has local reverent attention',cand='candidate_weak',conf='medium',crit='sustained_scene')
add('AC20','defiant_resistant',1,'productivity-obsessed age makes surrender feel criminal, but resistance is secondary',cand='candidate_weak',conf='medium',crit='thesis_level_affect')
add('AC21','elegiac_wistful',2,'unfinished letters/books/conversations and unresolved selves organize the sample',conf='high',crit='thesis_level_affect')
add('AC21','bright_wonder',2,'beauty in imperfect/not-yet/rehearsal-room possibility gives active wonder',conf='medium',crit='affective_landing')
add('AC21','warm_tender',1,'enoughness and generosity toward incompletion give mild warmth',cand='candidate_weak',conf='medium',crit='affective_landing')
add('AC22','defiant_resistant',2,'stop rushing through thresholds/dead time; transition as point resists destination logic',conf='high',crit='thesis_level_affect|affective_landing')
add('AC22','anxious_threatened',2,'thresholds lack narrative certainty and are feared; parking garages/waiting rooms carry unease',conf='high',crit='repeated_framing')
add('AC22','elegiac_wistful',1,'liminal becoming/who we were has local time-transition wistfulness',cand='candidate_weak',conf='medium',crit='sustained_scene')
add('AC22','bright_wonder',1,'possibility/potential/alive gives local wonder but not dominant',cand='candidate_weak',conf='medium',crit='affective_landing')
add('AC22','quiet_reverent',1,'stillness/holding breath in liminal spaces gives low reverence',cand='candidate_weak',conf='medium',crit='sustained_scene')
add('AC23','quiet_reverent',2,'pre-dawn blue, secret calm, being present while light changes structure the piece',conf='high',crit='repeated_framing|affective_landing')
add('AC23','warm_tender',1,'small stolen hour carried as calm into day gives mild comfort',cand='candidate_weak',conf='medium',crit='affective_landing')
add('AC23','anxious_threatened',1,'fear of silence and weight of performance are background pressure',cand='candidate_weak',conf='medium',crit='sustained_scene')
add('AC23','defiant_resistant',1,'presence before world demands performance is a small resistance',cand='candidate_weak',conf='medium',crit='affective_landing')
add('AC24','quiet_reverent',3,'4am hush, tea in dark, silence relenting into birdsong organizes sacred-still mood',conf='high',crit='sustained_scene|affective_landing')
add('AC24','bright_wonder',2,'ordinary miracle of another day and secret-club dawn imagery sustain gentle wonder',conf='medium',crit='affective_landing')
add('AC24','warm_tender',1,'kettle comfort and inclusive list of night-wakers provide mild warmth',cand='candidate_weak',conf='medium',crit='sustained_scene')
add('AC25','elegiac_wistful',2,'blue minutes, fading light, vanishing into night, transitions/ambiguous becoming',conf='high',crit='repeated_framing|affective_landing')
add('AC25','anxious_threatened',2,'lostness, guards down, anxious Tuesdays, uncertainty loosening grip shape the climate',conf='medium',crit='repeated_framing')
add('AC25','bright_wonder',2,'blue hour beauty and visible truth in half-light create wonder',conf='medium',crit='sustained_scene')
add('AC25','quiet_reverent',1,'world holds its breath; softened transition gets reverent attention locally',cand='candidate_weak',conf='medium',crit='sustained_scene')
add('AC25','resigned_fatalistic',1,'soft vanishing/dissolving into night suggests weighted acceptance',cand='candidate_weak',conf='low',crit='affective_landing')

# Add metadata from selection
meta={}
with open(OUT/'pilot_selection_and_prescreen.tsv') as f:
    for r in csv.DictReader(f, delimiter='\t'):
        meta[r['pilot_id']]=r
cols=['pilot_id','sample_id','model','condition','is_fiction','narrator_posture_carries_affect','storyworld_affect_present','dimension','candidate_level','rating_0_3','confidence','triggered_criteria','evidence_note','confounds','storyworld_affect_dimensions','storyworld_affect_rating_0_3','fiction_evidence_role','narrative_motif_flags','coder_id','rating_version']
with open(OUT/'mira_affective_pilot_ratings.tsv','w',newline='') as f:
    w=csv.DictWriter(f, fieldnames=cols, delimiter='\t')
    w.writeheader()
    for r in rows:
        m=meta[r['pilot_id']]
        out={c:'' for c in cols}
        out.update(r)
        out['sample_id']=m['sample_id']; out['model']=m['model']; out['condition']=m['condition']
        w.writerow(out)
print('wrote', len(rows), 'rating rows')
